### ISSUE TITLE
MaxPool tracking issue

### ISSUE THREAD

**Issue by jasonmorton** [zkonduit/ezkl#155]
- [x] Naive max pool implementation (range check for each cell of each window)
- [x] More optimized but still exact implementation
- [ ] Approximate but highly optimized implementation
